# Generated by Django 5.0.6 on 2024-06-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinosTuristicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCiudad', models.CharField(max_length=100)),
                ('imagenCiudad', models.ImageField(upload_to='pics')),
                ('descripcionCiudad', models.TextField()),
                ('precioTour', models.IntegerField()),
                ('ofertaTour', models.BooleanField(default=False)),
            ],
        ),
    ]
